name: Deploy Node.js App to Elastic Beanstalk

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: npm ci
    - run: npm test
    
    - name: Generate deployment package (zip entire backend directory, prod environment vars configured in AWS ELB)
      run: zip -r backend

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.DEPLOY_APPLICATION_NAME }}
        environment_name: ${{ secrets.DEPLOY_ENVIRONMENT_NAME }}
        version_label: "monarch-api-${{ github.sha }}"
        region: ${{ secrets.DEPLOY_AWS_REGION }}
        deployment_package: build.zip
